Demo on combining metrics.
pyroteus/animate pull request #62
Opened 2024-01-03 16:17 UTC by stephankramer

2024-01-04 08:01 UTC, jwallwork23 requested changes
Thanks very much for this, nice demo! I have a few requests but they are mostly just formatting.

2024-01-04 08:01 UTC, jwallwork23 commented on demos/combining_metrics.py
> +# .. figure:: combining_averaging.jpg :figwidth: 90% :align: center
I think these might need to be on separate lines? The image doesn't appear when I build the html.

2024-01-05 14:12 UTC, stephankramer commented
Thanks, Joe. Addressed all points I think and rebased.

2024-01-06 15:46 UTC, jwallwork23 approved these changes

2024-01-06 15:46 UTC, merged